<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>conllu</string>
		<string>conll</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^# .+$</string>
	<key>foldingStopMarker</key>
	<string>^ *$</string>
	<key>name</key>
	<string>ConLL-U</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^# .+$</string>
			<key>name</key>
			<string>comment.line.number-sign.conllu</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.id.conllu</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>markup.list.unnumbered.feats.conllu</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.other.form.conllu</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.other.lemma.conllu</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.language.upostag.conllu</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.xpostag.conllu</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>markup.list.unnumbered.feats.conllu</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.head.conllu</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>keyword.control.deprel.conllu</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>markup.list.numbered.deps.conllu</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)</string>
			<key>name</key>
			<string>entity.name.section.token.conllu</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.conllu</string>
	<key>uuid</key>
	<string>09964e2a-8d28-43cf-88e3-905e8305bee6</string>
</dict>
</plist>
